const { createDonationSource, normalizeDonation } = require('../src/donations/source');
const t = Date.parse('2026-10-09T10:00:00Z');
const raw = (i, extra={}) => ({donationID:'id'+i, participantID:12, amount:0.1, createdDateUTC:new Date(t-i*1000).toISOString(), ...extra});
const response = (items, count, status=200) => ({status, ok:status===200, headers:new Headers(count===undefined?{}:{'Num-Records':String(count)}), json:async()=>items});
const setup = pages => { const fetch=jest.fn(); pages.forEach(p=>fetch.mockResolvedValueOnce(p)); const source=createDonationSource({fetch,requestGapMs:0,clock:{nowMs:()=>t+1000}}); return {source,fetch}; };
test('newest-first one page and explicit zero offset/version', async()=>{ const {source,fetch}=setup([response([raw(1)],1)]); const latest=jest.fn(); const {scan}=await source.poll({participantId:'12',window:{fromMs:t-5000,throughMs:t},onLatest:latest}); expect(scan.donations).toHaveLength(1); expect(fetch.mock.calls[0][0]).toContain('offset=0'); expect(fetch.mock.calls[0][0]).toContain('version=1.4'); expect(latest).toHaveBeenCalledTimes(1); expect(fetch).toHaveBeenCalledTimes(1); });
test('conditional catch-up retrieves more than 100 gifts and stops at session start', async()=>{ const {source,fetch}=setup([response(Array.from({length:100},(_,i)=>raw(i)),200),response(Array.from({length:100},(_,i)=>raw(i+100)),200)]); const {scan}=await source.poll({participantId:12,window:{fromMs:t-139000,throughMs:t}}); expect(scan.donations).toHaveLength(140); expect(fetch).toHaveBeenCalledTimes(2); expect(fetch.mock.calls[1][0]).toContain('offset=100'); });
test('full newest page already passes window start: no history request', async()=>{ const {source,fetch}=setup([response(Array.from({length:100},(_,i)=>raw(i)),300)]); const {scan}=await source.poll({participantId:12,window:{fromMs:t-1000,throughMs:t}}); expect(scan.donations).toHaveLength(2); expect(fetch).toHaveBeenCalledTimes(1); });
test('page failure never completes accounting and newest page still reaches notifications', async()=>{const {source}=setup([response(Array.from({length:100},(_,i)=>raw(i)),150),response({},0,500)]);const latest=jest.fn(); await expect(source.poll({participantId:12,window:{fromMs:t-200000,throughMs:t},onLatest:latest})).rejects.toThrow();expect(latest).toHaveBeenCalledTimes(1);});
test('changing counts and repeated full pages fail rather than claim completeness', async()=>{for (const second of [response(Array.from({length:100},(_,i)=>raw(i)),200),response([raw(101)],201)]) {const {source}=setup([response(Array.from({length:100},(_,i)=>raw(i)),200),second]);await expect(source.poll({participantId:12,window:{fromMs:t-200000,throughMs:t}})).rejects.toThrow();}});
test('missing metadata uses short pages; contradictory short pages fail', async()=>{const {source}=setup([response([raw(1)])]);expect((await source.poll({participantId:12,window:{fromMs:0,throughMs:t}})).scan.complete).toBe(true);const b=setup([response([raw(1)],5)]);await expect(b.source.poll({participantId:12,window:{fromMs:0,throughMs:t}})).rejects.toThrow();});
test('204 empty window succeeds; non-array/error/304 responses reject',async()=>{const {source}=setup([response(null,0,204)]);expect((await source.poll({participantId:12,window:{fromMs:0,throughMs:t}})).scan.donations).toEqual([]); for (const res of [response({}),response(null,0,304),response(null,0,429)]){const b=setup([res]);await expect(b.source.poll({participantId:12,window:{fromMs:0,throughMs:t}})).rejects.toThrow();}});
test('strict zoned timestamps and participant/registration/amount validation',()=>{expect(normalizeDonation(raw(1,{createdDateUTC:'2026-10-09T10:00:00.123+0000'}),12,t+1000).createdAtMs).toBe(t+123);expect(normalizeDonation(raw(1,{amount:null}),12,t).amountCents).toBeNull();for(const extra of [{createdDateUTC:'2026-02-30T10:00:00Z'},{createdDateUTC:'2026-10-09T10:00:00'},{participantID:13},{isRegFee:true},{amount:1.111},{donationID:''},{createdDateUTC:'2027-01-01T00:00:00Z'}]) expect(()=>normalizeDonation(raw(1,extra),12,t)).toThrow();});
test('campaign validation; failed aggregate does not prevent a separate donation scan',async()=>{const {source}=setup([response({sumDonations:12.34,fundraisingGoal:500})]);expect(await source.readCampaign({participantId:12})).toMatchObject({totalCents:1234,goalCents:50000});});
test('cancellation and stopped sources cannot request',async()=>{const {source,fetch}=setup([]);const signal=AbortSignal.abort();await expect(source.poll({participantId:12,signal})).rejects.toThrow();source.stop();await expect(source.readCampaign({participantId:12})).rejects.toThrow();expect(fetch).not.toHaveBeenCalled();});

test('identical duplicate IDs in a page count once',async()=>{const {source}=setup([response([raw(1),raw(1)],2)]);expect((await source.poll({participantId:12,window:{fromMs:0,throughMs:t}})).scan.donations).toHaveLength(1);});
test('request pacing and backoff wait are cancellable',async()=>{let now=t;const wait=jest.fn(async ms=>{now+=ms;});const fetch=jest.fn().mockResolvedValue(response([],0));const source=createDonationSource({fetch,clock:{nowMs:()=>now},requestGapMs:15000,wait});await source.poll({participantId:12});await source.poll({participantId:12});expect(wait).toHaveBeenCalledWith(15000,undefined,expect.objectContaining({signal:expect.any(AbortSignal)}));source.stop();await expect(source.poll({participantId:12})).rejects.toThrow();});
